### ISSUE TITLE
开源协议是什么 QUANTAXIS可以整合你这个公式吗

### ISSUE THREAD

**Issue by yutiansut** [Alexdachen/ivix#1]
在公共号里看到的  可以整合你的公式吗  
https://github.com/QUANTAXIS/QUANTAXIS

**Comment by Alexdachen** [comment]
刚刚加了协议上来。公式是整合是可以的。
QUANTAXIS这个项目我也十分感兴趣呢。是用于证券方面的量化研究的嘛？有空也好好研究一下您的项目。

**Comment by Alexdachen** [comment]
这个项目有部分代码，获取数据的这部分代码我没有开源的，因为这个是接了wind接口，所以开源了对于大部分人而言未必用得上，后续会写一个爬虫的接口替代。

**Comment by yutiansut** [comment]
@Alexdachen ok 谢谢啦  数据quantaxis有的
